  web:
        build: .
        ports:
        - "8000:8000"
        links:
        - redis
  redis:
        image: redis
        command: redis-server --appendonly yes
        volumes: 
        - ./data:/data

